### ISSUE TITLE
Topic Download Support [Milestone 1] - Save Topics from Json to Offline Storage

### ISSUE THREAD

**Issue by rt4914** [oppia/oppia-android#1088]
This issue is tracking the milestone 1 topic download support.

Design Document: https://docs.google.com/document/d/1QSEzBhh_V7dtdnIs2kG2tRgADjBoYEPMzvvuwr0NjFc/edit

Currently in the domain layer, all the topics, stories, exploration, chapters, subtopics, skills, questions etc. are fetched directly from JSON files. There are various retrieve functions to convert these json files into their respective models like:
`TopicController.kt`
 - `fun retrieveTopic(topicId: String): Topic`
 - `fun retrieveStory(storyId: String): StorySummary`
All this data is finally sent to app layer in the form of LiveData<AsyncResult<<Any>>

We need to save all the json files data to proto-database and then retrieve that in various functions so that it can be used in app layer again.

At the end of this issue completion, the json files should directly save data to proto-database and the app layer should be getting data from the proto-database (instead of JSON files) via domain layer controllers.

# Repository Introduction
- [ ] Introduce `SkillRepository` which saves json data in proto-database and introduce functions which can be used to fetch data from this database.
- [ ] Introduce `SubtopicRepository` which saves json data in proto-database and introduce functions which can be used to fetch data from this database.
- [ ] Introduce `StoryRepository` which saves json data in proto-database and introduce functions which can be used to fetch data from this database.
- [ ] Introduce `ChapterRepository` which saves json data in proto-database and introduce functions which can be used to fetch data from this database.
- [ ] Introduce `TopicRepository` which saves json data in proto-database and introduce functions which can be used to fetch data from this database.

# Update existing controllers
- [ ] Create/Update new fetching functions in `TopicController`
- [ ] Create/Update new fetching functions in `StoryProgressController`
- [ ] Create/Update new fetching functions in `TopicListController`

# App layer changes
- [ ] Use updated/new functions from `TopicController`, `TopicListController` and `StoryProgressController` in domain layer.

# Remove unused protos, functions and test cases
- [ ] Remove all unused code and protos
