### ISSUE TITLE
Documentation Creation [GSoC'20][Milestone 3] 

### ISSUE THREAD

**Issue by Sarthak2601** [oppia/oppia-android#1108]
Creation of an authentic and well descriptive documentation regarding -

- [x] Steps to use Firebase Console. 
- [x] Steps to create own Firebase project.
- [x] Steps to create filtered Dashboards in future. 
- [x] Funnels and how to create them 
- [x] Addition of Custom Parameters 
- [x] User Properties 

Documentation -- [Firebase Console Guide](https://www.google.com/url?q=https://github.com/oppia/oppia-android/wiki/Firebase-Console-Guide&sa=D&source=hangouts&ust=1599265399087000&usg=AFQjCNExpFQPW2AFQCIgFJ8Jy5VyXWzwEA)

**Comment by Sarthak2601** [comment]
[Firebase Console Guide](https://github.com/oppia/oppia-android/wiki/Firebase-Console-Guide)

**Comment by Sarthak2601** [comment]
Added everything in the guide, hence closing this issue and marking as done.

**Comment by rt4914** [comment]
@Sarthak2601 Please mention the documentation link.

**Comment by Sarthak2601** [comment]
> @Sarthak2601 Please mention the documentation link.

@rt4914, I had mentioned it in the comments above. Added to the main description now.
