### ISSUE TITLE
Final UI: Topic play tab fragment [Blocked: #15, #137]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#140]
This is tracking implementing the high fidelity UI for the topic play tab.

Mock Link: https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/94a5f38c-e475-4514-8784-0e42cf70c25e/TP-Play-Scrolled-Up-

## Task Checklist

- [ ] `Stories You Can Play` text, along with line separators in between story-items (Assigned to @rt4914 )
<img width="329" alt="Screenshot 2019-11-07 at 4 00 43 PM" src="https://user-images.githubusercontent.com/9396084/68468726-989ee700-023e-11ea-8b29-90f8cd4d5ab6.png">

- [ ] Story Progress UI in following 3 cases, 100% progress story (Fully Finished), 0% progress story (Not yet started) and 33% progress story (partial completion) (or some double digit based percentage) (Assigned to @rt4914 )
<img width="72" alt="Screenshot 2019-11-07 at 4 00 51 PM" src="https://user-images.githubusercontent.com/9396084/68468669-7efd9f80-023e-11ea-9c7c-1f2e52b9443c.png">
<img width="59" alt="Screenshot 2019-11-07 at 4 00 58 PM" src="https://user-images.githubusercontent.com/9396084/68468674-802ecc80-023e-11ea-8db6-4e0be1e8046c.png">

- [ ] Story Summary Item including chapter count is correctly aligned and dropdown is functional with appropriate animations (if needed). (Assigned to @rt4914 )
<img width="317" alt="Screenshot 2019-11-07 at 4 01 16 PM" src="https://user-images.githubusercontent.com/9396084/68468661-7c9b4580-023e-11ea-9c25-4c793348979a.png">

- [ ] Chapter Summary Item including `tick` if the chapter is completed and correct chapter color. Chapter color is based on following points:
- If Chapter is finished: BLACK (`What is a Fraction?` in mocks)
- If Chapter is in Progress: BLACK (`The Meaning of "Equal Parts"` in mocks)
- If Chapter is not yet started: GREY (`Fractions of a Group` in mocks) (Assigned to @rt4914 )
<img width="309" alt="Screenshot 2019-11-07 at 4 01 27 PM" src="https://user-images.githubusercontent.com/9396084/68468643-74430a80-023e-11ea-819a-fdc139a35e14.png">

- [ ] Full story item along with drop down animation (Assigned to @rt4914 )
<img width="330" alt="Screenshot 2019-11-07 at 4 05 02 PM" src="https://user-images.githubusercontent.com/9396084/68468706-8f157f00-023e-11ea-8d12-d40882106993.png">

- [ ] Final integration of whole fragment. (Assigned to @rt4914 )

- [ ] Accessibility Scanner is working correctly (Assigned to @rt4914 ) (https://support.google.com/accessibility/android/answer/6376570?hl=en)

**Comment by BenHenning** [comment]
This is blocked on #137 for structure and #15 for full domain functionality.

**Comment by BenHenning** [comment]
@rt4914 can you clarify what remaining work needs to be done here?

**Comment by rt4914** [comment]
WIP in #486

**Comment by rt4914** [comment]
This was finished with the last PR being #1465  (animation PR.)
