### ISSUE TITLE
Final UI: Topic overview tab fragment [Blocked: #15, #136]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#141]
This is tracking implementing the high fidelity UI for the topic overview tab.

https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/19cfbacf-854c-4c7d-8691-3b3d117e1866/TP-Overview-

## Task List

- [x] Topic thumbnail (Image) with gradient over image (without topic-name) (Assigned to @veena14cs )
<img width="327" alt="Screenshot 2019-10-31 at 6 17 29 PM" src="https://user-images.githubusercontent.com/9396084/67947983-c1095e80-fc0a-11e9-92af-6eb016a22125.png">

- [ ] Topic content including topic-name, story-count, topic description
<img width="323" alt="Screenshot 2019-10-31 at 6 17 37 PM" src="https://user-images.githubusercontent.com/9396084/67947990-c4044f00-fc0a-11e9-96d2-76c6936626d5.png">

- [x] See More text  and Download Status (Assigned to @veena14cs )
<img width="327" alt="Screenshot 2019-11-07 at 3 30 29 PM" src="https://user-images.githubusercontent.com/9396084/68379267-91f76d80-0173-11ea-8a0f-a9bd922ee019.png">
<img width="238" alt="Screenshot 2019-11-07 at 3 29 24 PM" src="https://user-images.githubusercontent.com/9396084/68379202-74c29f00-0173-11ea-92a3-5cb42a9108a7.png">

- [ ] Final integration and final touch-up

- [ ] Accessibility Scanner is working correctly (https://support.google.com/accessibility/android/answer/6376570?hl=en)

**Comment by BenHenning** [comment]
This is blocked on #136 for structure and #15 for full domain functionality.

**Comment by veena14cs** [comment]
@rt4914 @BenHenning @nikitamarysolomanpvt I will work on 1st task Topic thumbnail (Image) with gradient over image (without topic-name)

**Comment by veena14cs** [comment]
@rt4914 @BenHenning @nikitamarysolomanpvt I will be working on 3rd task See More text and story downloaded information.

**Comment by veena14cs** [comment]
@rt4914 I will take up all the tasks from this issue.
