### ISSUE TITLE
Add support for Dagger Hilt [Blocked: #59]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#1720]
**Is your feature request related to a problem? Please describe.**
The team is currently limited when creating test-only dependencies: either we need to blur the lines between modules by adding dependencies to the test-only testing module, or we need to include test-only dependencies in the production build of the app due to Dagger & manifest requirements.

**Describe the solution you'd like**
Dagger Hilt https://dagger.dev/hilt/ solves this & other problems (like simplifying test application code in tests) by automatically generating components based on what's included in the build graph. This pairs extremely nicely with Bazel, so this issue can be considered blocking on #59.

**Describe alternatives you've considered**
The alternatives would be:
1. Not making this improvement & living with the current situation
2. Rolling out our own code gen
3. Investigate an alternative to Dagger that solves the underlying component issue & doesn't introduce runtime reflection requirements

(2) & (3) would require a potentially enormous amount of work, and (1) doesn't solve the underlying problem.

**Comment by adhiamboperes** [comment]
Finally got around to prototyping this. TLDR; Hilt does work with our versions of Gradle and Bazel.

## Purpose
Create means for reusing dagger modules in tests

## Resources:
https://medium.com/androiddevelopers/dagger-navigation-support-in-android-studio-49aa5d149ec9 
https://developer.android.com/codelabs/android-dagger-to-hilt#0 

## Todo
- Verify that Hilt is supported on our project.
    - Hilt is supported in Android Studio 4.0 or higher. We use Arctic Fox and Bumblebee, which are newer than 4.0.
    - Hilt works with our versions of Bazel(6.5.0) and Gradle(6.8), AGP 4.2.2.
- How to add Hilt to the project: keep Dagger and Hilt working side by side during the migration by keeping the app functional while migrating each Dagger component to Hilt.
   - Add Hilt dependencies https://developer.android.com/training/dependency-injection/hilt-android#setup 
   -  Add Hilt to Bazel
## Migration strategy
- Application or @Singleton component first, and later migrate activities and fragments.
    -   ApplicationComponent first
    -   Annotate all modules with @InstallIn(start with Application level modules and app module modules)
    -   Remove all @Component and @Subcomponent interfaces
    -   After the migration, all Application/Activity/Fragment/View/Service/BroadcastReceiver classes should be annotated with @AndroidEntryPoint and any code instantiating or propagating components should also be removed.
    -   Migrate Test files to Hilt

## Compatibility issues during migration

1. [InteractionViewModelModule.kt](https://github.com/oppia/oppia-android/blob/develop/app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/InteractionViewModelModule.kt) attempts to use both binds & provides methods, but Dagger doesn’t usually support this. (@Binds is usually used in abstract classes or interfaces only, while @Provides method requires a return type). A workaround was implemented for this: https://github.com/oppia/oppia-android/blob/96f5289456de80b91a79ad82fd94e2e789f0e39b/app/src/main/java/org/oppia/android/app/player/state/itemviewmodel/InteractionViewModelModule.kt#L80-L93
Hilt requires all modules annotated with @InstallIn(SingletonComponent::class). In this case, both the companion and enclosing class need that annotation. This however, causes Hilt build to fail with: 

```
/Users/adhiambooyier/Developer/AndroidStudioProjects/opensource/oppia-android/app/build/generated/source/kapt/debug/org/oppia/android/app/application/AbstractOppiaApplication_HiltComponents.java:163: error: org.oppia.android.app.player.state.itemviewmodel.InteractionViewModelModule.Companion is listed as a module, but it is a companion object class. Add @Module to the enclosing class and reference that instead.
          InteractionViewModelModule.Companion.class,
```

_**The solution is to remove the @InstallIn(SingletonComponent::class) and the @Module annotations from the companion. Manual testing revealed all interactions working correctly.**_


## Pending Protoyping Work:
- [ ] Migrate exposed types: creating `EntryPoint` interfaces for hooking up Hilt to activities and fragments.
- [ ] Migrating Activities/Fragment components.
- [ ] Migrating other scoped components.
- [ ] unit tests
- [ ] UI tests
- [ ] Migrating ViewModels
