### ISSUE TITLE
Introduce Authentication Flow [Blocked till offline work gets done]

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#1818]
Design for creating multi-profile accounts on Oppia Android & logging in (including authentication).
As Oppia-web is having a Google authentication setup, we need to implement a similar feature in the Oppia-android as well.

### TODO
- [x] Check how does auth flow works in the web part
     `// will be adding the data flow soon`
- [ ] Brief understanding of data/domain module in order to know how the current networking things work in Oppia android
      `We are going to use ProfileManagementController majorly. Adding new profile  - profileManagementController.addProfile(). All the model classes and services will go in the data package.  API will be named as *Service.kt and model classes named as Gae*.kt. Proto files will go in the model package. `
- [ ] Complete [Design Doc](https://docs.google.com/document/d/1FGnJwKS4B5-acGjd58aKNJmG1UYFal6Wm7mQdGQCehM/edit?usp=sharing)
     - [ ] Finalize the user flow -> screens/mocks
     - [ ] Finalize the outcomes of this feature -> what will be the end goal looks like
     - [ ] Review from Reviewers
- [ ] Complete Tech Doc
     - [ ] Check-in deep about the current auth APIs/Storage models what are the other things will be required will mention here to keep track
     - [ ] Create a proper implementation steps
     - [ ] Review from Reviewers
- [ ] Complete all the UI/HiFi work - only designing, no data binding etc
     - [ ] create a list of UI files need, after finalizing design doc
- [ ] Complete all LowFi work
    - [ ] create a list of small working implementation like server connection, all proto added etc
- [ ] Work on documentation in parallel which helps other developers to understand the codebase/data flow

### Reference 

- [Full Remote Profile Support Project](https://docs.google.com/document/d/1sQagy3irkjB1Kt5sdb_KkOgxODt2m2ya0ZCoSJNlY4A/edit?usp=sharing)

### Tips

- Create other smaller documentation of ongoing work/applied approaches/failure/type of crashes for deep understanding and add the same in the final documentation
- Create data flow charts

### How the flow works in the web platform

```
main.py
    URLS = get_redirect_route() // URL mapping
    def get_redirect_route(regex_route, handler, defaults=None)
    // handler - a class which is extended by base.py
```

```
base.py
1. current_user_services -> import from models.py
from core.platform.users import gae_current_user_services

2. get user model
elif name == NAMES.user:
      from core.storage.user import gae_models as user_models
      returned_models.append(user_models)

3. class BaseHandler
get gae_id from gae_current_user_services.py // if the email already exist app engine will return gae_id else 
it will create a new gae_id and returns the new gae_id for that particular user. 
self.gae_id = current_user_services.get_current_gae_id()
```

```
get the user's user_setting from user_services.py which uses gae_models.py to get the data, if the user_setting is none(a new/first time user) then create profile for this new user
user_settings = user_services.get_user_settings_by_gae_id(self.gae_id, strict=False)

def get_user_settings_by_gae_id(gae_id, strict=False)

def get_by_auth_id(cls, auth_service, auth_id):

// create new user
user_settings = user_services.create_new_user(self.gae_id, email)
```
