### ISSUE TITLE
Final UI: Topic activity/fragment [Blocked: #15]

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#23]
The topic page should provide background information on the topic, skills corresponding to the topic (which link to the concept card for that skill), navigation to training on skills in the topic, the progress of stories the user has played in that topic, and links to stories (with preference for in-progress/immediately upcoming stories, though all stories should be viewable). See the PRD for specifics.

Note that this is tracking implementing the final UI for just the topic page. The final UIs for each constituent tab is indicated as a blocker of this issue.

https://xd.adobe.com/spec/e2239cf4-9cde-4c08-5296-25316c1f0a14-9412/screen/19cfbacf-854c-4c7d-8691-3b3d117e1866/TP-Overview-

## Task Items
- [ ] Hamburger Icon and Toolbar/ActionBar title
<img width="323" alt="Screenshot 2019-11-05 at 9 26 38 PM" src="https://user-images.githubusercontent.com/9396084/68223558-01a21700-0013-11ea-84c2-3d50ed5c85aa.png">

- [ ] TabLayout with icons and titles
<img width="322" alt="Screenshot 2019-11-05 at 9 26 45 PM" src="https://user-images.githubusercontent.com/9396084/68223562-04047100-0013-11ea-8d5e-d419ad5d313c.png">

- [ ] Final check on all fragments and final touch-up

- [ ] Accessibility Scanner is working correctly (https://support.google.com/accessibility/android/answer/6376570?hl=en)

**Comment by BenHenning** [comment]
This is blocked on #15.

**Comment by BenHenning** [comment]
@rt4914 can you clarify what remaining work needs to be done here?

**Comment by rt4914** [comment]
#140 animation is pending and also, @mschanteltc as discussed earlier, the icons in tabs are not looking good, we need updated icons/svgs mostly square in shape.
<img width="359" alt="Screenshot 2019-12-02 at 11 57 30 PM" src="https://user-images.githubusercontent.com/9396084/69984623-84a98500-155f-11ea-9a29-a31e36852e7c.png">

**Comment by mschanteltc** [comment]
I updated the icons so that they are all 24 px, meaning that some icons that are not equal in height and width have padding in the svg file. Does this resolve the issue?

**Comment by rt4914** [comment]
> I updated the icons so that they are all 24 px, meaning that some icons that are not equal in height and width have padding in the svg file. Does this resolve the issue?

@mschanteltc Check this  https://github.com/oppia/oppia-android/pull/505#issuecomment-560532261

**Comment by rt4914** [comment]
This issue can be closed as it has been fixed via #995 & #505
