### ISSUE TITLE
Complete the TODO Wiki sections for Static Checks

### ISSUE THREAD

**Issue by Sparsh1212** [oppia/oppia-android#3690]
Presently there are some TODOs left in the static analysis Wiki.
- [ ] Java lint check
- [ ] Kotlin lint check
- [ ] Protobuf lint check
- [ ] Bazel lint check
- [ ] Completing the section "Adding a new static analysis check"
- [x] Add a section on running static checks locally

We should complete writing the documentation for these sections.

**Comment by anandwana001** [comment]
Let's connect the [Static Analysis Checks Wiki Page](https://github.com/oppia/oppia-android/wiki/Static-Analysis-Checks) with the already written wiki pages. 

Ktlint (Kotlin) - https://github.com/oppia/oppia-android/wiki/Ktlint-Guide
Protobuf (Proto) - https://github.com/oppia/oppia-android/wiki/Buf-Guide
Checkstyle (Java) - Required a wiki page
Buildifier (Bazel) - Required a wiki page

**Comment by adhiamboperes** [comment]
I think we should also add a section on how to run the static checks locally. This comes up a lot in the team. 

@MohitGupta121: Would you be able to do a wiki update with this information? We recorded these in the May 23 meeting notes.

**Comment by MohitGupta121** [comment]
@adhiamboperes sorry for late reply, I missed this comment. 
I have to write "How to run static checks locally" such as Java lint check, Kotlin lint check, Protobuf lint check, Bazel lint check in these TODO's present in this [wiki](https://github.com/oppia/oppia-android/wiki/Static-Analysis-Checks#java-lint-check) ? Can you please breif. Thanks!

**Comment by adhiamboperes** [comment]
@MohitGupta121, you only need to add one new section at the bottom of this page under "How to add a new Static analysis check". You do not have to create a seperate one for each check.

You can call it "Running static checks locally" as you have suggested. 

The contents would be:
1. Finding the correct command  to run from the CI check on github
2. Finding the correct command to run from android studio

**Comment by MohitGupta121** [comment]
Okay thanks you so much @adhiamboperes understood.

**Comment by MohitGupta121** [comment]
Okay thanks you so much @adhiamboperes understood.
So can I file new issue for this to keep track?
Or I can assign this particular issue to me?

**Comment by adhiamboperes** [comment]
You can assign this and do a "Fix part of 3690:" PR.
