### ISSUE TITLE
RTL Exempted file fixes

### ISSUE THREAD

**Issue by viktoriias** [oppia/oppia-android#3775]
`file_content_validation_checks.textproto` contains regex pattern checks to spot prohibited content. Some files are listed as `exemplted_file_name` because they contain prohibited elements . This is a tracking issue to fix exempted files that violate RTL rules.  We should change those attributes to make it RTL compatible. For example, in `add_profile_activity.xml`: replace `layout_constraintRight_toRightOf` with `layout_constraintEnd_toEndOf`

Files to be updated:
  - [x] add_profile_activity.xml (tracked in https://github.com/oppia/oppia-android/issues/3807)
  - [x] profile_progress_header.xml (tracked in https://github.com/oppia/oppia-android/issues/3808)
  - [x] styles.xml (tracked in https://github.com/oppia/oppia-android/issues/3809)
  - [x] topic_practice_subtopic.xml - fixed in Sample PR: (https://github.com/oppia/oppia-android/pull/3776).

RTL guidelines: https://github.com/oppia/oppia-android/wiki/RTL-Guidelines

Please add screenshots when creating a PR with both LTR and RTL views on mobile + tablet.
