### ISSUE TITLE
Add basic learner analytics support

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4064]
PRD: https://docs.google.com/document/d/13H_r47Ge6dj_VAszEHQttoyOoCKXeEgodSTv16-7fnY/edit.

Between #4247 and #4248, remaining work items I've identified:
- [x] Disable the feature by default
- [x] Verify that event uploading is actually happening, and correctly, to Firebase
- [x] Shift the implementation such that the domain changes update modules, but don't actually change the application classes until the integration PR (revised to 4 PRs: domain components, integration, events, UI)
- [x] Generating device ID using a GUID that's persisted on disk (this is a **requirement change** since we've discovered that we can't rely on hardware identifiers)
- [x] Update event logging flow to be asynchronous since the device ID has to be persisted on disk and thus can't be retrieved synchronously (see previous item) -- Update: only the IDs part needs to be asynchronous (which conveniently builds nicely into existing controllers now that using ``StateFlow`` is on the table since I branched the PRs off of math expressions).
- [ ] Finish implementing the remaining events, and make sure they're thoroughly tested
- [x] Session ID needs to be piped using data providers (which might introduce a situation where we actually block on #4239 which would not be ideal)
- [ ] All tests need to be checked to pass on Gradle & Bazel
- [ ] Affected UI tests need to be tested with Espresso via Gradle
- [x] We may potentially need the Bazel test fixes introduced in #4068 since these PRs are affecting so many tests it's causing the compute affected tests workflow to fail
- [x] Any other comments I've listed in #4247 and #4248
- [x] Figure out the chaining & merge strategy for the project since changes are sort of messily split between the two PRs (maybe partly because of earlier merging challenges). It'd be nice to keep PR reviews as simple as possible, but the priority needs to be execution speed.
- [x] Since new branches are going to be created per the merging strategy, ensure all the changes from the early project are fully covered within those branches

Statuses on all of the events that need to be added:
- [x] Card Start: not started as of the opening of this issue
- [x] Card End: not started as of the opening of this issue
- [x] Hint Offered: not started as of the opening of this issue
- [x] Hint Accessed: not started as of the opening of this issue
- [x] Solution accessed: not started as of the opening of this issue
- [x] Solution offered: not started as of the opening of this issue
- [x] Submit answer: not started as of the opening of this issue
- [x] Play voice over: not started as of the opening of this issue
- [x] Background app inactivity: not started as of the opening of this issue
- [x] Foreground app: not started as of the opening of this issue
- [x] Exit exploration: not started as of the opening of this issue
- [x] Finish lesson: started to be logged as of the opening of this issue, but needs to be fixed & tested
- [x] Resume lesson: not started as of the opening of this issue
- [x] Click “Start Over” on resume: not started as of the opening of this issue
- [x] Delete profile: not started as of the opening of this issue

Items listed in the TDD that I'm not implementing to save time (these are being dropped as requirements)
- Implementing last synced time in the UI
- Implementing a snackbar for when text is copied in the admin panel (this doesn't seem necessary anymore since the button transitions to a 'copied' state; it seems super clear)

**Comment by BenHenning** [comment]
Copying the remaining tasks from https://github.com/oppia/oppia-android/pull/4247#issuecomment-1070877735 to the PR description.

Beyond that, I think I'm going to use the following branch structure to try and keep the reviews smaller and hopefully easier:
- learner-analytics-pt4-domain-components
- learner-analytics-pt5-new-events
- learner-analytics-pt6-new-ui
- learner-analytics-pt7-integration

I'm also planning to chain this onto #2173. Even though algebraic expressions aren't required in MR4, that PR will be going into review later today (the project should be done barring 1 issue I've found). There are a bunch of infrastructure changes and fixes in those changes that will need to be replicated later in the learner analytics work, and it potentially simplifies and/or unblocks learner analytics work (such as the issue with Bazel, and some of the cross-thread communication stuff).
