### ISSUE TITLE
Fast-follow MR4 work items (writing tests)

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#4345]
This issue is tracking smaller work items that were intentionally postponed to expedite the MR4 release given tight scheduling and resourcing constraints. As a result, there may be cases when some tests weren't added. We should add those tests.

The open work items are tracked below:

- [x] Address all TODOs attached to this issue.
- [x] Make sure PR #4274 has good testing coverage.
- [x] Make sure PR #4259 has good testing coverage.
- [x] Make sure PR #4307 has good testing coverage.
- [x] Make sure PR #4271 has good testing coverage.

-----

Note: These work items were originally in this issue when it was first filed, but have since been closed (no further action is needed here):
- Resolve #4266
- Resolve #4265
- Resolve #4344

Also, some PR descriptions also need to be updated. These are tracked separately in https://github.com/oppia/oppia-android/issues/5038.

---
The following TODOs are left out to close the issue, which can be resolved in seperate PRs:

> // TODO(#4345): Add tests to verify this behavior both for the study flag being on & off. 

- [ ] The following tests could be considered for inclusion in AdministratorControlsFragmentTest
  - `testAdministratorControlsFragment_studyFlagEnabled_profileAndDeviceIdSectionIsDisplayed`
  - `testAdministratorControlsFragment_studyFlagDisabled_profileAndDeviceIdSectionIsNotDisplayed`

> // TODO(#4345): Add test for this method. 

- [ ] The following tests could be considered for inclusion in TextViewBindingAdaptersTest
  - `testSetDrawableTopCompat_withDrawable_setsDrawableAtTop`
  - `testSetDrawableTopCompat_withNullDrawable_clearsTopDrawable`

> // TODO(#4345): Block on the following data provider before allowing the user to log in. 
- [ ] Following steps need to be taken care of:
- Make initializeLearnerId() return an observable result
- Chain login after successful initialization
- Add error handling for initialization failures

> // TODO(#4345): Add tests for this & other math expression classifiers to verifying that rule 

- [ ] The following tests could be considered for inclusion in NumericExpressionInputMatchesExactlyWithRuleClassifierProviderTest

  - `testMatches_expressionWithRedundantOuterParentheses_returnsTrue`
  - `testMatches_expressionWithNestedRedundantParentheses_returnsTrue`
  - `testMatches_expressionWithMultipleLayersOfRedundantParentheses_returnsTrue`
  - `testMatches_expressionWithNonRedundantParenthesesDifference_returnsFalse`
  - `testMatches_expressionWithParenthesesAffectingOperatorPrecedence_returnsFalse`
  - `testMatches_expressionWithOnlyParenthesesAroundNumber_returnsTrue`
  - `testMatches_expressionWithMismatchedParentheses_returnsFalse`

> // TODO(#4345): Add tests for this method. 

- [ ] The following tests could be considered for inclusion in MathExpressionExtensionsTest

  - `testStripRedundantGroups_singleConstantInGroup_returnsConstant`
  - `testStripRedundantGroups_singleVariableInGroup_returnsVariable`
  - `testStripRedundantGroups_nestedSingleTermGroups_returnsSimplifiedExpression`
  - `testStripRedundantGroups_expressionWithRedundantParenthesesAroundBinary_returnsSimplifiedExpression`
  - `testStripRedundantGroups_binaryOperationInGroup_returnsUnchangedExpression`
  - `testStripRedundantGroups_unaryOperationInGroup_returnsUnchangedExpression`
  - `testStripRedundantGroups_functionCallInGroup_returnsUnchangedExpression`
  - `testStripRedundantGroups_alreadySimplifiedExpression_returnsSameExpression`
  - `testStripRedundantGroups_emptyExpression_returnsSameExpression`

**Comment by BenHenning** [comment]
This needs to be bumped back to help expedite the initial beta release.

**Comment by adhiamboperes** [comment]
Hi @BenHenning, PTAL, looks like all the TODOs here have been closed.

**Comment by BenHenning** [comment]
Thanks @adhiamboperes. It does look like this can be closed now.

**Comment by BenHenning** [comment]
Ah, it apparently isn't yet resolved @adhiamboperes. The above TODOs are what remains to address.

**Comment by manas-yu** [comment]
> // TODO(#4345): Add tests to verify this behavior both for the study flag being on & off. 

The following tests could be considered for inclusion in AdministratorControlsFragmentTest
- `testAdministratorControlsFragment_studyFlagEnabled_profileAndDeviceIdSectionIsDisplayed`
- `testAdministratorControlsFragment_studyFlagDisabled_profileAndDeviceIdSectionIsNotDisplayed`

> // TODO(#4345): Add test for this method. 

The following tests could be considered for inclusion in TextViewBindingAdaptersTest
- `testSetDrawableTopCompat_withDrawable_setsDrawableAtTop`
- `testSetDrawableTopCompat_withNullDrawable_clearsTopDrawable`

> // TODO(#4345): Block on the following data provider before allowing the user to log in. 

- Make initializeLearnerId() return an observable result
- Chain login after successful initialization
- Add error handling for initialization failures

> // TODO(#4345): Add tests for this & other math expression classifiers to verifying that rule 

The following tests could be considered for inclusion in NumericExpressionInputMatchesExactlyWithRuleClassifierProviderTest

- `testMatches_expressionWithRedundantOuterParentheses_returnsTrue`
- `testMatches_expressionWithNestedRedundantParentheses_returnsTrue`
- `testMatches_expressionWithMultipleLayersOfRedundantParentheses_returnsTrue`
- `testMatches_expressionWithNonRedundantParenthesesDifference_returnsFalse`
- `testMatches_expressionWithParenthesesAffectingOperatorPrecedence_returnsFalse`
- `testMatches_expressionWithOnlyParenthesesAroundNumber_returnsTrue`
- `testMatches_expressionWithMismatchedParentheses_returnsFalse`

> // TODO(#4345): Add tests for this method. 

The following tests could be considered for inclusion in MathExpressionExtensionsTest

- `testStripRedundantGroups_singleConstantInGroup_returnsConstant`
- `testStripRedundantGroups_singleVariableInGroup_returnsVariable`
- `testStripRedundantGroups_nestedSingleTermGroups_returnsSimplifiedExpression`
- `testStripRedundantGroups_expressionWithRedundantParenthesesAroundBinary_returnsSimplifiedExpression`
- `testStripRedundantGroups_binaryOperationInGroup_returnsUnchangedExpression`
- `testStripRedundantGroups_unaryOperationInGroup_returnsUnchangedExpression`
- `testStripRedundantGroups_functionCallInGroup_returnsUnchangedExpression`
- `testStripRedundantGroups_alreadySimplifiedExpression_returnsSameExpression`
- `testStripRedundantGroups_emptyExpression_returnsSameExpression`
