### ISSUE TITLE
Android App - Onboarding Flow for learners and teachers/parents

### ISSUE THREAD

**Issue by tanzhirong** [oppia/oppia-android#4938]
**Is your feature request related to a problem?**
Profile onboarding experience is especially confusing for single-person device users. For example, users may be confused about when an administrator profile is required, and what differentiates a learner from an administrator. In addition, selection of key settings (e.g. language, audio) are currently missing from the onboarding flow.

**Describe the solution you'd like A clear and concise description of what you want to happen.**
The goal is to ensure that even without external assistance from an Oppia facilitator, users (either supervisors or learners)  (1) are well aware of the app’s value proposition, and (2) could (or in the case of supervisors, enable their students or children to) easily start his/her first lesson. These include features such as:
- Differentiating a learner from an administrator (e.g. teachers/parents) at the start of the onboarding flow
- Provide clear guidance on what the administrator does
- Allow users to set up the preferred settings (e.g. audio, language) in the onboarding process
- Ensure flow is easy to understand when a user (either the supervisor or the original learner) wants to add more learner profiles

Note that this project should be tackled in 3 parts in the following order (more details are in the "Implementation Process" section of the [PRD](https://docs.google.com/document/d/1th_V3ykAS-mUP5HjclMwO-CTxINarqgBaKBOqiGXNf4/edit#heading=h.liiqbmwmz8j8)):
- [x] Implement the onboarding flow for a learner profile.
- [x] Implement the onboarding "account type" selection.
- [ ] Implement the administrative account settings.
- [ ] Ensure compatibility with dark mode and accessibility tools

**Describe alternatives you've considered**
There are other features looking at audio/language change, but this request focuses on the onboarding flow.
Other alternatives include improved copywriting (which has been included in the proposed solution).

**Additional context Add any other context or screenshots about the feature request here.**

- PRD: https://docs.google.com/document/d/1th_V3ykAS-mUP5HjclMwO-CTxINarqgBaKBOqiGXNf4/edit#heading=h.liiqbmwmz8j8
- Mocks and Flow: https://www.figma.com/file/PnCtQKDR5VWbIlA3Ui7rTa/Oppia---Onboarding-Android-App?type=design&node-id=1446-11977&mode=design&t=6XYSCmBZqJCm6NA7-0
   - Old mocks here: https://docs.google.com/presentation/d/1cdvX9HUXuqJsV53odRM0TZlPA1EHOW3tpjK_tGpR73U/edit#slide=id.g1584efe35cd_0_270

### Milestone 1 and 2

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-9b4cef22-7fff-4916-3815-c58c1d3e3524"><div dir="ltr" style="margin-left:0pt;" align="left">
No. | Description of PR / action | Prereq PR numbers | Target date for PR creation | Target date for PR to be merged
-- | -- | -- | -- | --
1 | Create the gating platform parameterIncludes tests in the platform parameter modules | None | 03/11/23 |  ✅
2 | Create the new UI layout files | None | 10/11/23 |  ✅
3 | App Language Selection onboarding- Add the flow for configuring app language and gate it behind the onboarding platform parameter- Add tests | 1, 2 | 15/11/23 |  ✅
4 | Add logic to gate the old onboarding vs new onboarding flow on app launch, based on the onboarding platform parameter value- Add tests | 1 | 17/11/23 |  ✅
5 | Add the profile type screen flow and tests | 3 | 22/11/ 23 |  ✅
6 | Profile configuration- Add logic for configuring new profile types and gating this behind the onboarding platform parameter | 4 | 4/12/23 |  ✅
7 | Add the sole learner profile creation flow- Issue #4803 should be resolved | 5,6 | 8/12/23 |  ✅
8 | Add welcome page flow | 7 | 11/12/23 |  ✅
9 | Audio language selection logic- Includes navigation to the learner home screen | 8 | 15/12/23 |  ✅
10 | Demo to PMs/stakeholders: New sole learner onboarding flow when the onboarding platform parameter is enabled. | 9 | 19/12/23 |  ✅
11 | Existing profile migration | 9 | 22/12/23 |  ✅
12 | Non-onboarding flow login logic- Sole learners- Other existing profiles | 11 | 10/01/24 |  ✅
13 | Demo to PMs/stakeholders: Non-onboarding flow and existing profile migration | 12 | 23/01/24 |  ✅

</div></b>

### Milestone 3 and 4

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-29e37123-7fff-8ce5-a101-bc44044e1a61"><div dir="ltr" style="margin-left:0pt;" align="left">
No. | Description of PR / action | Prereq PR numbers | Target date for PR creation | Status
-- | -- | -- | -- | --
1 | Language Configuration to set admin language as global language. | None | 11-Sept-25 |
2 | Trigger the Admin onboarding flow | None | 24-Sept-25 | ✅
3 | Refactor the profile creation screen to have admin-specific copy. | 2 | 9-Oct-25 | ✅
4 | Redesign the Enter PIN(login) screen | None | 21-Aug-25 | ✅
5 | Redesign the PIN creation screen | 3 | 19-Dec-25 | #5880 
6 | Remove the default admin | None | 23-Sept-2025 | ✅
7 | Create the new additional profile creation flow | 4 | 08-Jan-2026 | #6048 
  | Demo to PMs/stakeholders: Video demo of the admin profile onboarding flowVideo demo of the the additional learner flow with handover to learner |   | 12-Jan-2026 |  
8 | Create the sole learner drawer menu | None | 19-Jan-2026 |
9 | Create the sole learner to supervisor migration flow | 8 | 19-Dec-2025 | #6049 
10 | Add new spotlights | None | 19-Dec-2025 | #6028 
  | Demo to PMs/stakeholders: Video demo of the complete redesigned onboarding flowProfile Migration demoNew Profiles demo |   | 26-Jan-2026 |  

</div></b>

**Comment by adhiamboperes** [comment]
Hi @tanzhirong, could you add a summary of the issue/feature description  in addition to the links?

**Comment by MohitGupta121** [comment]
@adhiamboperes I think this issue is from this particular issue #4627 

@tanzhirong we need to add this flow in oppia-android wiki?

**Comment by adhiamboperes** [comment]
> @adhiamboperes I think this issue is from this particular issue #4627
> 
> @tanzhirong we need to add this flow in oppia-android wiki?

@MohitGupta121, I believe this is to track the fix to #4627, and is not implemented yet so we will not be adding it to the Wiki. 
I'd like @tanzhirong  to add a description in the issue body so that it is clear what the feature request is asking.

**Comment by BenHenning** [comment]
/cc @seanlip 

Keep in mind that "onboarding" is a bit overloaded in this context. :) We're both working to revise the technical onboarding flow for Oppia Android developers, as well as the in-app onboarding flow for learners & parents/teachers. I suspect a clearer description would be very helpful to better clarify that this is corresponding to the latter.

@tanzhirong we have an existing feature request template that you can follow. See: https://github.com/oppia/oppia-android/blob/develop/.github/ISSUE_TEMPLATE/feature_request.md

(you can copy it from https://raw.githubusercontent.com/oppia/oppia-android/develop/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by tanzhirong** [comment]
Hi all, thanks! Have updated the description accordingly.
