### ISSUE TITLE
Master tracking issue for prototype branch cut 3

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#494]
This issue is tracking all of the work we want to include in our third prototype branch cut, including work items that should not be submitted onto develop. All work items here are based on the corresponding [workstream](https://github.com/oppia/oppia-android/issues?page=1&q=is%3Aissue+is%3Aopen+label%3A%22Workstream%3A+Finalize+Prototype+pt2+%2820-30+Nov%29%22) for this branch cut.

Current PRs that are being targeted:
- [x] Audio fixes (#358)
- [x] Profile system (#269, #326, #327, #328)
- [x] #493 (elevation fix)
- [x] #492 (add content & change thumbnail image for ratios concept card)
- [x] #350 (remove temp data)
- [x] #397 (training controller impl)
- [x] #422 (show concept cards in explorations)
- [x] #500 (question training fragment)
- [x] #498: Update leave dialog text
- [x] #495: Align continue buttons
- [x] Maybe: audio highlighting (#491)
- [x] Maybe: error detection for fractions (#419)
- [x] Maybe: updated RecyclerView for home fragment (#477)
- [ ] Maybe: #418 (submit button color -- needs updating)
- [ ] Maybe: #486 (topic play animation)
- [ ] Maybe: #490 (bullet list improvements)

Issues that are expected to be fully resolved from the above list of PRs:
- #16
- #433
- #431
- #387
- #377
- #370
- #307
- #159
- #111
- #47
- #44
- #164 (maybe)
- #140 (maybe)
- #23 (maybe)

Issues that require additional work after the above:
- [ ] #434 (core experience is janky -> requires more animation work in state fragment)
- [ ] #428 (num/denom concept card missing images -> requires updating the JSON with images)
- [ ] #376 (interaction validation -> after fractions, numeric input needs validation support)
- [ ] #360 (finalize UIs for smaller screens -> after profiles is done, need to topic play tabs & list)
- [x] #425 (fraction answer submission sometimes breaks)
- [x] #499 (right alignment of user feedback looks incorrect)

Issues that may require additional work but whose additional work is unclear:
- [ ] #42 (exp fragment/activity full UI -> not sure what work remains)
- [ ] #40 (questions final UI -> likely out of scope)
- [ ] #35 (end exploration full UI -> not sure what work remains)
- [ ] #34 (continue button interaction full UI -> need to display continue button name from customization args/not in scope)
- [ ] #24 (concept card final UI -> not sure what work remains)

Other work that needs to be done on temp branch that shouldn't be checked in:
- [x] Hardcode profiles
- [x] Enable caching

**Comment by BenHenning** [comment]
FYI: The work items tracked here are the priority items. We should aim to submit fixes for all of these by EOD PST Monday 2 December / EOD IST Tuesday 3 December.

**Comment by BenHenning** [comment]
NB: The 'maybe' targets will be resolved based on how much progress we make on these items by the target Monday/Tuesday submission dates.

**Comment by rt4914** [comment]
@BenHenning #418 is not solving the Submit button issue. It was created correctly but the approach was incorrect and the approach suggested by you, I was not able to correctly work on that to solve the issue, so it is kind of stuck.

**Comment by BenHenning** [comment]
Ack thanks @rt4914. We might avoid trying to get that in today due to other higher priority fixes being needed.

**Comment by BenHenning** [comment]
Issues that we observed while testing & developing:
- [x] Images are occasionally cut off in exploration & question players (expected fix: #507)
- [x] Fractions fails validation for mixed numbers (e.g. '3 1/2' for second state of Meaning of Equal Parts) (expected fix: changes in #419 + #510)
- [x] Fractions fails submission for some numbers (e.g. '1/2' for second state of Meaning of Equal Parts) (expected fix: #510)
- [x] Audio is not correctly autoplaying when enabled and moving to a new state (expected fix: #515)
- [x] Audio content card highlighting isn't working (expected fix: #514)
- [ ]  Images are not properly being cached in all cases, and not at all for questions
- [ ] We need to turn off the internet restriction for audio streaming on the temp branch for the meaning of equal parts since we are caching audio locally for that lesson (expected fix already on temp-integration-pt3)
- [ ] Image relayouting causing jankiness in both exploration and question player (works fine on 5X, now janky on ZTE)
- [x] Previous answers not properly recollapsing in the question player (#511) (fixed directly on branch)
- [x] ~Questions player currently renders questions like an exploration rather than like the mocks~ (not feasible to fix for temp branch)
- [x] ~Questions player does not track right-on-first-try nor report that at the end of the session~ (not feasible to fix for temp branch)
- [x] ~LaTeX expressions are not rendering correctly (#513)~ (not feasible to fix for temp branch)
- [x] ~Item selection allows submission when no items are selected (#512)~ (not fixing in temp branch: not a bad bug, and unlikely to be found)

----

Other bugs found after additional testing:
- [ ] Bullet points look weird on mdpi devices
- [x] We're missing a concept card link when entering 4/5 on the third state of Meaning of Equal Parts
- [ ] Ratios concept card is janky on mdpi devices because it gets cut-off
- Image loading is janky on slower devices (this is being tracked above since it wasn't fully solved)
- [x] LaTeX text is noticeable (unlike above, the goal here is to replace the text with non-LaTeX rather than introduce LaTeX support)
- [x] Line breaking happens sometimes in unexpected places, especially on mdpi devices
- [x] It's unexpected that the end of the questions training session can scroll on mdpi devices

**Comment by BenHenning** [comment]
Note that progress in this issue corresponds to fixes on temp-integration-pt3, not develop. We will start cutting lower priority breakages. This branch can be viewed in #506.

**Comment by BenHenning** [comment]
Priority items:
- LaTeX removal
- Concept card link
- Ratios concept card spacing
- Line break improvements
- Fix offline trigger (it's set for the wrong exploration)

Stretch:
- Bullet list fixes

**Comment by BenHenning** [comment]
NB: content highlighting now seems to be working correctly.

**Comment by rt4914** [comment]
@BenHenning Bullets have been improvised to support MDPI as well XHDPI and other devices.
Code updated in #490

**Comment by BenHenning** [comment]
Thanks @rt4914! I'll merge that in the temp branch again and verify it on the device we originally noticed it on.

**Comment by BenHenning** [comment]
@rt4914 they look a bit better, but I think we still need to move the bullet list a bit lower since it seems to be aligned on the top of the line, and that causes a larger visual discrepancy on a mdpi device.

**Comment by rt4914** [comment]
@BenHenning Okay, I will check and update once again.

**Comment by rt4914** [comment]
> @rt4914 they look a bit better, but I think we still need to move the bullet list a bit lower since it seems to be aligned on the top of the line, and that causes a larger visual discrepancy on a mdpi device.

Just updated #490 . Check this comment: https://github.com/oppia/oppia-android/pull/490#issuecomment-561987360

**Comment by BenHenning** [comment]
All work here has either been completed or is now being tracked as part of a milestone.
