### ISSUE TITLE
Add Cloud Firestore to the App

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5001]
## Add Firebase Firestore
This issue tracks milestone 7 of the NPS Survey.

- [x] Add bazel and gradle dependencies for Firestore 
- [x] #5130
- [x] Rig up the app to upload data to Firestore on our existing log upload pipeline.

### Writing to Firestore
Collections and Documents in Firestore are created implicitly on first write. For our use case, we are creating collections at the root level of our database to organize unique data sets. This means we are going to have one collection with the name nps_survey_open_feedback for storing answers to the open-ended survey responses, and should we want to store different data in the future, we will create a new collection for it.

We will add the following data to the document:

- survey_id: String. This is the id of the survey with which this free text answer is associated. 
- open_feedback_answer:  String. The value of the answer provided by the user.
- time_submitted: Long. We are storing a timestamp as a field in the documents to use for ordering in queries. We will also mark this field as a TTL field for automatic data deletion per the retention policy.

We are using the Firestore `add()` method as opposed to `set()` in order for Firestore to auto generate our document Ids, which need not be meaningful. This will also enforce uniqueness during write so that a user is unable to overwrite any other user’s document.

## Authenticate with Firebase anonymously
We are implementing anonymous auth in the background to allow users to be authenticated with Firebase Security Rules.

## Tasks
- [x] Configure Anonymous Auth
- [x] Configure Firestore upload
- [ ] Test security rules
- [x] Test offline auth, storage and upload

**Comment by Gdakgdak22** [comment]
> ## Add Firebase Firestore
> This issue tracks milestone 7 of the NPS Survey.
> 
> - [x] Add bazel and gradle dependencies for Firestore 
> - [x] Create a new cache store for storing Firestore data when the app is offline.
> - [x] Rig up the app to upload data to Firestore on our existing log upload pipeline.
> 
> ### Writing to Firestore
> Collections and Documents in Firestore are created implicitly on first write. For our use case, we are creating collections at the root level of our database to organize unique data sets. This means we are going to have one collection with the name nps_survey_open_feedback for storing answers to the open-ended survey responses, and should we want to store different data in the future, we will create a new collection for it.
> 
> We will add the following data to the document:
> 
> - survey_id: String. This is the id of the survey with which this free text answer is associated. 
> - open_feedback_answer:  String. The value of the answer provided by the user.
> - time_submitted: Long. We are storing a timestamp as a field in the documents to use for ordering in queries. We will also mark this field as a TTL field for automatic data deletion per the retention policy.
> 
> We are using the Firestore `add()` method as opposed to `set()` in order for Firestore to auto generate our document Ids, which need not be meaningful. This will also enforce uniqueness during write so that a user is unable to overwrite any other user’s document.
> 
> ## Authenticate with Firebase anonymously
> We are implementing anonymous auth in the background to allow users to be authenticated with Firebase Security Rules.
> 
> ## Tasks
> - [x] Configure Anonymous Auth
> - [x] Configure Firestore upload
> - [ ] Test security rules
> - [x] Test offline auth, storage and upload
>
