### ISSUE TITLE
[BUG]: Missing tests from Beta MR1

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5035]
Some PRs that were merged for the Beta MR1 release (in Sep 2022) have additional tests that need to be written. These are described below:

**Contributors:** Please pick one checkbox and write at least one test for it (as a demo). Then, post a comment below with your chosen checkbox + the test code for that test to get assigned. Thanks!

- [ ] **#4418**: Add thorough tests for all cases, including verifying the exit and profile deletion behaviors for the UI

  - **PinPasswordActivity / PinPasswordActivityPresenter**
    - ~`testPinPassword_withAdmin_forgetPin_showsConfirmDataResetDialog`~
    - ~`testPinPassword_withAdmin_forgetPin_confirmDataReset_deletesAllProfiles`~
    - ~`testPinPassword_withAdmin_forgetPin_confirmDataReset_routesToSplashActivity`~
    - ~`testPinPassword_withAdmin_forgetPin_cancelDataReset_dismissesDialog_profilesRemain`~
    - ~`testPinPassword_withAdmin_forgetPin_afterReset_profileChooserIsEmpty`~
    - ~`testPinPassword_withAdmin_forgetPin_afterReset_localeIsNotReset`~

  - **ProfileChooserViewModel**
    - `testProfileChooser_afterDataReset_showsEmptyProfileList`
    - `testProfileChooser_afterDataReset_selectingProfile_doesNotCrash`

  - **SplashActivityPresenter**
    - `testSplashActivity_afterDataReset_localeInitialization_skippedIfAlreadySet`
    - `testSplashActivity_afterDataReset_recreatesActivitySuccessfully`

  - ~**ProfileManagementController**~
    - ~`testProfileManagementController_deleteAllProfiles_profilesListIsEmpty`~
    - ~`testProfileManagementController_deleteAllProfiles_inMemoryCacheUpdated`~
    - ~`testProfileManagementController_deleteAllProfiles_preservesNonProfileData`~

- [ ] **#4555**: Many tests needed both for the updated/new domain functionality and for all of the changed UIs to verify that translations are correctly used  

  **The types of tests needed per section:**

  - **Domain Layer**
    - Unit tests for controllers to verify translated vs. fallback strings.
    - Unit tests for translation computation logic (with/without supported language).
    - Unit tests to ensure titles/descriptions are correctly computed as translated strings.
    - Fallback behavior tests when translations are missing.

  - **UI Layer**
    - Instrumentation/UI tests to confirm translated text is shown in activities/fragments (topics, stories, chapters, subtopics, explorations).
    - UI tests for fallback to untranslated strings.

  - **Profile ID Refactoring**
    - Unit tests to confirm passing `ProfileId` retrieves correct translations.
    - Negative tests where no `ProfileId` → fallback behavior.

  - **ViewModel Refactoring (part of #1051)**
    - Unit tests ensuring presenters with injected view models do not leak memory.
    - Lifecycle tests to confirm translation state survives configuration changes.
    
- [ ] **#4411**: Add tests to cover the new recreation behaviors, and add more thorough tests for `FontScaleConfigurationUtil` (since it doesn't work in certain cases & requires a recreation)  

  **The tests needed fall into four specific sections:**

  - **FontScaleConfigurationUtil & Recreation Behavior**
     - Unit tests verifying that `FontScaleConfigurationUtil` correctly recomputes scaled density.
     - UI/Instrumentation tests confirming that `recreate()` causes text size updates to actually apply immediately in lessons.
     - Regression tests ensuring text size remains consistent after checkpoints, re-login, and returning from the options menu.

  - **Reading Text Size Selection (Proto-based Typing)**
     - Unit tests for proto enum mapping (size ↔ display value).
     - UI/Instrumentation tests validating that selecting a text size works correctly for both English and non-English languages.
     - Negative tests verifying fallback when translations are missing or corrupted.

  - **ParentScreen Proto Enum Refactor**
     - Unit tests confirming correct propagation of `ParentScreen` enum in exploration navigation flows.
     - Integration tests checking round-trip navigation between activities (RecentlyPlayed → Exploration, Options → Exploration).

  - **Intent Extras & Result Handling**
     - Espresso tests using the new `hasProtoExtra` matcher to validate proto payloads passed via intents.
     - UI tests verifying `ReadingTextSizeActivity` returns the correct proto in its result bundle.

The aim of this issue is to write these tests.

(This issue was originally part of #4567 but has been split out to isolate the "missing tests" action items.)

**Comment by nikhilkumarpanigrahi** [comment]
Hi @seanlip , I'd like to work on the **ProfileManagementController** checkbox:

- `testProfileManagementController_deleteAllProfiles_profilesListIsEmpty`
- `testProfileManagementController_deleteAllProfiles_inMemoryCacheUpdated`
- `testProfileManagementController_deleteAllProfiles_preservesNonProfileData`

### What I'm changing

| File | Change |
|------|--------|
| `domain/src/test/java/org/oppia/android/domain/profile/ProfileManagementControllerTest.kt` | Add 3 new test methods for `deleteAllProfiles()` |

### Why

`ProfileManagementController.deleteAllProfiles()` (source line 1053) currently has **zero test coverage**. Existing tests only cover individual `deleteProfile()`. These tests verify that bulk deletion clears the profile list, removes directories, and logs analytics events.

### Demo test code

```kotlin
@Test
fun testDeleteAllProfiles_addProfiles_deleteAllProfiles_profilesListIsEmpty() {
  setUpTestApplicationComponent()
  addTestProfiles()

  val deleteProvider = profileManagementController.deleteAllProfiles()
  monitorFactory.waitForNextSuccessfulResult(deleteProvider)
  // Force the app to "restart" so the in-memory cache reloads from disk.
  setUpTestApplicationComponent()

  val profilesProvider = profileManagementController.getProfiles()
  val profiles = monitorFactory.waitForNextSuccessfulResult(profilesProvider)
  assertThat(profiles).isEmpty()
}

@Test
fun testDeleteAllProfiles_addProfiles_deleteAllProfiles_profileDirectoriesAreRemoved() {
  setUpTestApplicationComponent()
  addTestProfiles()

  val deleteProvider = profileManagementController.deleteAllProfiles()
  monitorFactory.waitForNextSuccessfulResult(deleteProvider)

  PROFILES_LIST.indices.forEach { idx ->
    assertThat(File(getAbsoluteDirPath(idx.toString())).isDirectory).isFalse()
  }
}

@Test
fun testDeleteAllProfiles_addProfiles_deleteAllProfiles_logsDeleteEventsForAllProfiles() {
  setUpTestApplicationComponentWithLearnerAnalyticsStudy()
  addTestProfiles()

  monitorFactory.ensureDataProviderExecutes(
    profileManagementController.deleteAllProfiles()
  )

  assertThat(fakeAnalyticsEventLogger.getEventListCount()).isEqualTo(PROFILES_LIST.size)
}
```

**Comment by BenHenning** [comment]
@nikhilkumarpanigrahi you don't need to write the whole tests for this, but I am a bit confused: why are you writing tests that don't correspond to the three that are needed for `ProfileManagementController`?

**Comment by nikhilkumarpanigrahi** [comment]
Hi @BenHenning, I'm sorry for the mismatch! I mistakenly wrote tests for unrelated behaviors instead of the three named in the issue. Here's a corrected demo for the first one:

```kotlin
@Test
fun testProfileManagementController_deleteAllProfiles_profilesListIsEmpty() {
  setUpTestApplicationComponent()
  addTestProfiles()

  profileManagementController.deleteAllProfiles().ensureExecutes()
  // Restart to reload from disk (in-memory cache is not updated per the docstring).
  setUpTestApplicationComponent()

  val profiles = monitorFactory.waitForNextSuccessfulResult(
    profileManagementController.getProfiles()
  )
  assertThat(profiles).isEmpty()
}
```
I'll write the other two (inMemoryCacheUpdated, preservesNonProfileData) in the PR once assigned. Note that preservesNonProfileData may require a small fix to deleteAllProfiles() since it currently replaces the entire ProfileDatabase with getDefaultInstance(), which also clears device settings.

**Comment by adhiamboperes** [comment]
@nikhilkumarpanigrahi, I have assigned you the issue, please create a PR covering only the relevant tests.

**Comment by nikhilkumarpanigrahi** [comment]
@BenHenning @adhiamboperes PTAL

**Comment by Sandesh282** [comment]
Hi @seanlip, I'd like to work on the **ProfileChooserViewModel** checkbox:

- `testProfileChooser_afterDataReset_showsEmptyProfileList`
- `testProfileChooser_afterDataReset_selectingProfile_doesNotCrash`

### What I'm changing

| File | Change |
|---|---|
| [app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt](file:///Users/syndx/AndroidStudioProjects/opensource/oppia-android/app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt) | Add 2 new test methods for ProfileChooserViewModel after data reset |

### Why

The [`ProfileChooserFragmentTest.kt`](https://github.com/oppia/oppia-android/blob/develop/app/src/sharedTest/java/org/oppia/android/app/profile/ProfileChooserFragmentTest.kt) currently has no tests verifying its behavior after `ProfileManagementController.deleteAllProfiles()` is called. These tests ensure that the profile chooser UI correctly reflects an empty state post-reset and that interacting with the empty chooser does not crash.

### Demo test code

```kotlin
@Test
fun testProfileChooser_afterDataReset_showsEmptyProfileList() {
  TestPlatformParameterModule.forceEnableOnboardingFlowV2(false)
  setUpTestApplicationComponent()
  profileTestHelper.initializeProfiles(autoLogIn = false)
  testCoroutineDispatchers.runCurrent()

  // Perform data reset by deleting all profiles.
  profileManagementController.deleteAllProfiles()
  testCoroutineDispatchers.runCurrent()

  launch(ProfileChooserActivity::class.java).use {
    testCoroutineDispatchers.runCurrent()
    // Verify that no profile items are shown in the recycler view (only the "add profile"
    // item should be present or the list should reflect an empty/reset state).
    onView(withId(R.id.profile_recycler_view))
      .check(matches(isDisplayed()))
    onView(
      atPositionOnView(
        recyclerViewId = R.id.profile_recycler_view,
        position = 0,
        targetViewId = R.id.profile_name_text
      )
    ).check(doesNotExist())
  }
}
```

I'll write both tests in the PR once assigned.

**Comment by BenHenning** [comment]
@Sandesh282 that seems like a reasonable approach--go ahead.

**Comment by adhiamboperes** [comment]
@Sandesh282, are you actively working on this issue?

**Comment by Sandesh282** [comment]
Hi @adhiamboperes, yes I'm still actively working on this! Apologies for the delay! I've been concurrently working on the [optimize lint execution PR (#6098)](https://github.com/oppia/oppia-android/pull/6098) which required a fair amount of back-and-forth on review comments, and that ended up taking more of my bandwidth than expected over the past few weeks. 

I've been focusing on the PR #4418 (App Data Reset Flow) tests -- specifically the `PinPasswordActivity`/`PinPasswordActivityPresenter` and `ProfileManagementController` sections, as well as scoping out the PR #4411 (Reading Text Size) tests around `FontScaleConfigurationUtil` & Recreation Behavior and the Intent Extras & Result Handling section.
I should be able to put up a PR covering the first batch of these soon. Thanks for checking in!

**Comment by Sandesh282** [comment]
@adhiamboperes Both #6125 and #6227 are merged now --covered the `ProfileChooserViewModel` reset tests, `FontScaleConfigurationUtil` recreation, intent/result handling, and proto enum mapping. The ParentScreen refactor section is still open, unassigning myself so someone else can pick it up in the meantime!
