### ISSUE TITLE
[BUG]: Fast-follow work items from MR4 (updating PR descriptions)

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-android#5038]
Because the MR4 release had to be expedited, we postponed updating some of the PR descriptions. This issue tracks the descriptions that need to be updated:

- [x] Finish the PR description for #4274
- [ ] Finish the PR description for #4259 -- (specifically to include details for #4319 and #4329)
- [x] Finish the PR description for #4307
- [x] Finish the PR description for #4271 (Edit, Adhiambo: Add tablet screenshots)

(Note: This issue was originally part of #4345 but has been split out to isolate the PR description work items from the tests.)
