### ISSUE TITLE
Oppia Android API 19 4.4.2 (Kitkat) UI issues.

### ISSUE THREAD

**Issue by nikitamarysolomanpvt** [oppia/oppia-android#530]
**Select your profile**
- [ ] Click events are not working /Hanging /Slaggy 

 **HomeFragment**
<img width="335" alt="Untitled" src="https://user-images.githubusercontent.com/54615666/70407829-d3798200-1a6b-11ea-828b-eb3dbc889275.png">

- [ ] Click events are not working /Hanging /Slaggy 

- [ ] Material Cards UI issues 

- [ ] Drop shadow  

- [ ] Card borders   

 **Story list (Continue Playing)**

- [ ] Click events are not working /Hanging /Slaggy

**Chapter List (Mathew goes..)**

<img width="342" alt="Untitled" src="https://user-images.githubusercontent.com/54615666/70408180-33245d00-1a6d-11ea-8431-fd1de4033c5e.png">

- [ ] Click events are not working /Hanging /Slaggy

- [x] Material Cards UI issues    (fixed by @nikitamarysolomanpvt #536)

- [x] Drop shadow   (fixed by @nikitamarysolomanpvt #536)

- [x] Card borders   (fixed by @nikitamarysolomanpvt #536)

 **Exploration** 

- [ ] Back button elivation/Drop shadow

- [ ] Image loads slowly

 **Audio bar UI**

<img width="286" alt="Untitled" src="https://user-images.githubusercontent.com/54615666/70408067-db85f180-1a6c-11ea-8951-6ce695189c9d.png">
- [ ] Color

- [ ] Seekbar height

- [ ] Thumb position

<img width="124" alt="Untitled" src="https://user-images.githubusercontent.com/54615666/70408102-f7899300-1a6c-11ea-9f60-c02181248a33.png">

- [ ] Back button click sometimes not working and on continuous click of both back button the leave topic dialog flicker and disappears.

 **Topic Tabs**
<img width="354" alt="Untitled" src="https://user-images.githubusercontent.com/54615666/70407931-497de900-1a6c-11ea-8963-7b1543470ec9.png">

- [ ] Text inactive tint/icon tint and boldness

 **Play**
<img width="355" alt="Untitled" src="https://user-images.githubusercontent.com/54615666/70407905-31a66500-1a6c-11ea-81b9-e31b8f3fcc50.png">

- [ ] Click events are not working /Hanging /Slaggy(except card expand)

- [ ] Dashed lines (fixed by @nikitamarysolomanpvt #627)

**Review** 

<img width="172" alt="Untitled" src="https://user-images.githubusercontent.com/54615666/70408227-5e0eb100-1a6d-11ea-833d-b6a61cb38c56.png">

- [x] Material Cards UI issues   (fixed by @nikitamarysolomanpvt #536)

- [x] Drop shadow   (fixed by @nikitamarysolomanpvt #536)

- [x] Card borders   (fixed by @nikitamarysolomanpvt #536)

 
**Suggestion** 

- [ ] Animation  on images and question player

**Comment by seanlip** [comment]
Per https://github.com/oppia/oppia-android/issues/5012, we are deprecating support for Android KitKat, so this issue is no longer valid.
