### ISSUE TITLE
[Feature Request]: Replace type-ambiguous (and now deprecated) Bundle calls

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#5405]
### Is your feature request related to a problem? Please describe.

API 33 (introduced in #5222) deprecated ``Bundle``'s generic methods:
- https://developer.android.com/reference/android/os/BaseBundle#get(java.lang.String).
- https://developer.android.com/reference/android/os/Bundle#getSerializable(java.lang.String)

#5402 helped reveal which places need updating:
- [ ] app/src/main/java/org/oppia/android/app/options/OptionsActivity.kt
- [ ] app/src/main/java/org/oppia/android/app/testing/TestFontScaleConfigurationUtilActivity.kt
- [ ] app/src/main/java/org/oppia/android/app/topic/practice/TopicPracticeFragment.kt
- [ ] utility/src/main/java/org/oppia/android/util/extensions/BundleExtensions.kt
- [ ] utility/src/test/java/org/oppia/android/util/extensions/BundleExtensionsTest.kt

### Describe the solution you'd like

Calls need to be replaced with either type-specific or ``BundleCompat`` calls, specifically:
- ``getSerializable()`` should now use https://developer.android.com/reference/androidx/core/os/BundleCompat#getSerializable(android.os.Bundle,java.lang.String,java.lang.Class%3CT%3E) instead.
- ``get()`` calls should be replaced with the 'get' method for the expected data type.

### Describe alternatives you've considered

None--``BundleCompat`` must be used for cases when we do not know the type since the app has a minimum supported SDK of 21.

### Additional context

The app generally uses Bundles in one of two cases:
- Navigating to fragments & activities.
- Performing configuration changes (such as a device rotation).

All changes to fragments and activities need to be tested by:
- Ensuring they functionally work when being navigated to.
- Ensuring they functionally work after rotations to portrait and landscape (both orientations should be tested, and functionality should be tested both before and after the orientation change).

Some special notes:
- The first work on this issue will require updating AndroidX core to a newer version.
- The changes in utility/src/test/java/org/oppia/android/util/extensions/BundleExtensionsTest.kt require updating Robolectric (which probably will need to happen out-of-band as it's complicated) in order to configure that test to run on SDK 33. Also, the idea here is to use a type check to verify the exact type (for a stronger assertion), e.g.:
  ```kotlin
  assertThat(intent.getSerializableExtra("first_extra")).isNotInstanceOf(String::class.java)
  ```
- The changes in utility/src/main/java/org/oppia/android/util/extensions/BundleExtensions.kt require replacing the ``getTypedSerializable`` helper method entirely as it's essentially reimplementing the method from ``BundleCompat``.
- Some of the type changes aren't trivial replacements as the semantics between casting a ``get()`` and using a type-specific method like ``getString`` are different: the former would throw an exception (if not using ``as?``) and the latter would become null. This needs to be considered while performing the migration work.

**Comment by uphargaur** [comment]
@adhiamboperes  can i work on this issue

**Comment by adhiamboperes** [comment]
@uphargaur, Sure.

**Comment by adhiamboperes** [comment]
@uphargaur, are you still working on this?

**Comment by uphargaur** [comment]
Yes I am working on it, sorry for delay got my exams this week.

**Comment by uphargaur** [comment]
@adhiamboperes  I tried working on it, but I’m finding it difficult to locate the data class. 

For example, in the image below, I'm unable to identify which class to use for reference. Could you help me find that, or should I create a data class depending on the use case?

![image](https://github.com/user-attachments/assets/cf942a15-1456-485f-89f5-9eaebca80277)

**Comment by adhiamboperes** [comment]
@uphargaur, I do not understand the question. What is data class in reference to?

**Comment by TanishMoral11** [comment]
Hey @adhiamboperes , can i work on this issue

**Comment by TanishMoral11** [comment]
Hello @adhiamboperes ,

I would like to work on this issue #5405. I have reviewed the requirements and would like to share my implementation approach:

### Implementation Plan

1. **Infrastructure Updates**
   - First, I will update AndroidX Core to version 1.15.0 ( Currently Used Version ) to access the new BundleCompat functionality
   - This will serve as the foundation for implementing the type-safe methods

2. **Core Changes**
   - Replace deprecated `getSerializable()` calls with `BundleCompat.getSerializable()`
   - Update generic `get()` calls with type-specific methods (e.g., `getString()`, `getInt()`)
   - Modify `BundleExtensions.kt` to remove `getTypedSerializable` helper method and implement BundleCompat alternatives

3. **Type Safety & Null Handling**
   - Add appropriate null safety checks where type-specific methods are introduced
   - Handle the behavioral change from exception-throwing to null returns

### Note on Robolectric Tests
I understand that updating `BundleExtensionsTest.kt` requires Robolectric updates, which should be handled separately. I will focus on the main implementation first.

### Questions
1. Should I create separate PRs for the AndroidX Core update and the main implementation?
2. Are there any specific components that should be prioritized in this update?

I would appreciate any feedback or additional guidance on this approach.

Thanks !!

**Comment by adhiamboperes** [comment]
Thanks for the detailed description @TanishMoral11! 

1. The issue description mentions the list of the files requiring changes, and since it’s a short list, I believe it’s okay to fix the full issue in one PR.
2. The list in the description should be adhered to.

Please let me know if you need further clarification.

**Comment by swarnalicoder** [comment]
Hello,
I’m a beginner in Android development and would love to contribute to this issue. I’ve been learning about Bundles and AndroidX, and I’m excited to help with replacing deprecated getSerializable() calls. Any guidance or resources to help me get started would be appreciated!
Looking forward to contributing!

**Comment by TanishMoral11** [comment]
Hey @swarnalicoder ,
 #### Welcome to the Oppia Community!

As a new member, please ensure that you have signed the Contributor License Agreement (CLA) to get started.

Currently, I am working on an issue, but I encourage you to explore and pick any issue labeled as **"Good First Issue."** This is a great opportunity for you to contribute and familiarize yourself with our project.

You can find these issues [here](https://github.com/oppia/oppia-android/issues?q=is%3Aissue+label%3A%22good+first+issue%22+is%3Aopen).

If you have any questions or need assistance, feel free to reach out. 
Happy coding!

**Comment by swarnalicoder** [comment]
Hi @TanishMoral11,

Thank you for the warm welcome! I'm excited to contribute to the Oppia community.

Could you please provide the link or guidance to sign the Contributor License Agreement (CLA)? I'd like to get started right away.

Thanks for your help!

**Comment by TanishMoral11** [comment]
Please check out the [contributor's wiki](https://github.com/oppia/oppia-android/wiki) to get started.
Also This Is Not Right Place For This . 
So You Can Ask Your Any Doubts In Github Discussion .

**Comment by shrimpnaur** [comment]
Is this issue closed? @TanishMoral11

**Comment by adhiamboperes** [comment]
@shrimpnaur, this issue is open. If you would like to work on it, please write a summary of the idea you have to solve it.

**Comment by akkicodes-dev** [comment]
Hi @adhiamboperes ! 
I've reviewed this issue and I understand that the codebase has several type-ambiguous and deprecated Bundle calls that need to be replaced with their type-safe modern equivalents. My approach would be to:

Search the codebase for all deprecated Bundle call usages
Replace each one with the correct type-safe alternative
Run tests to ensure nothing is broken after changes

Could you please assign this to me? I'll start immediately. Thank you!

**Comment by BenHenning** [comment]
@akkicodes-dev we've already listed the places that will need changes unless I'm missing something. Have you found anywhere else that needs to be updated?

One thing that would be helpful: how do you plan to approach the specific challenges listed in 'Additional context'? Those seem particularly noteworthy as it could be easy to get tripped up on them.

**Comment by akkicodes-dev** [comment]
Hey!  @BenHenning  Thanks for the clarification.

I reviewed the listed locations and will use them as the primary reference. I haven’t found additional occurrences beyond those yet, but I’ll keep checking as I go through the codebase.

For the challenges mentioned in the “Additional context”, my plan is:

- To carefully handle cases where Bundle calls have type ambiguity, ensuring the correct type-safe methods are used (e.g., matching exact data types instead of generic replacements).
- To watch out for edge cases where nullability or casting might affect behavior.
- To test each change incrementally to avoid breaking existing functionality.

Please let me know if there are any specific tricky cases you’d like me to prioritize.

I’d be happy to start working on this.

**Comment by BenHenning** [comment]
I'll assign this to you @akkicodes-dev but I want to make special note of the two lines in the issue description that state that AndroidX core and Robolectric may need upgrades. These can potentially be non-trivial and may result in this issue becoming blocked (e.g. on #4748 or #6021 -- unfiled parts of it will be tracking upgrading Kotlin which may be a prerequisite to upgrading to whichever AndroidX core version that we need here).
