### ISSUE TITLE
[Feature Request]: Test and Ensure App Support for Font Scaling up to 200%

### ISSUE THREAD

**Issue by theMr17** [oppia/oppia-android#5607]
### Is your feature request related to a problem? Please describe.

Android 14+ (SDK 34) supports **non-linear font scaling up to 200%** for accessibility. Oppia needs to be thoroughly tested to ensure the UI works correctly at larger font sizes. Currently, some screens (e.g., Topic Screen) show text truncation and overlap when scaled to 200%.  

### Describe the solution you'd like

We need to systematically test all **fragments/dialogs** in the app with **font scaling set to 200%** and fix any UI issues.  
This work will be split across multiple PRs, each responsible for ~5 fragments.  

Steps to test:  
1. On device/emulator, go to **System Settings > Accessibility > Display size and text**.  
2. Adjust **Font Size** slider to **200%**.  
3. Open the Oppia app and navigate to the listed fragments.  
4. Capture screenshots (and optional screen recording) of each screen.  
5. Fix issues such as text overlap, truncation, or misaligned UI elements.  

---

### Subtasks (each checkbox = 1 PR covering ~5 fragments)

- [ ] **PR 1:** Onboarding Flow  
  - OnboardingFragment  
  - OnboardingProfileTypeFragment  
  - CreateProfileFragment  
  - IntroFragment  
  - WalkthroughWelcomeFragment  

- [ ] **PR 2:** Walkthrough & Profile Setup  
  - WalkthroughTopicListFragment  
  - WalkthroughFinalFragment  
  - ProfileChooserFragment  
  - ProfileListFragment  
  - ProfileEditFragment  

- [ ] **PR 3:** Profile Management  
  - ProfileRenameFragment  
  - ProfilePictureEditDialogFragment  
  - ProfileProgressFragment  
  - ProfileResetPinFragment  
  - ResetPinDialogFragment  

- [ ] **PR 4:** Home & Navigation  
  - HomeFragment  
  - NavigationDrawerFragment  
  - RecentlyPlayedFragment  
  - OngoingTopicListFragment  
  - CompletedStoryListFragment  

- [ ] **PR 5:** Topic & Lessons  
  - TopicFragment  
  - TopicInfoFragment  
  - TopicLessonsFragment  
  - TopicPracticeFragment  
  - TopicRevisionFragment  

- [ ] **PR 6:** Exploration Flow  
  - ExplorationFragment  
  - StateFragment  
  - ResumeLessonFragment  
  - StopExplorationDialogFragment  
  - HintsAndSolutionDialogFragment  

- [ ] **PR 7:** Concept & Revision  
  - ConceptCardFragment  
  - RevisionCardFragment  
  - RevealSolutionDialogFragment  
  - HintsAndSolutionExplorationManagerFragment  
  - HintsAndSolutionQuestionManagerFragment  

- [ ] **PR 8:** Question Player & Practice  
  - QuestionPlayerFragment  
  - DragDropTestFragment  
  - ImageRegionSelectionTestFragment  
  - MathExpressionParserFragment  
  - MarkChaptersCompletedFragment  

- [ ] **PR 9:** Story & Downloads  
  - StoryFragment  
  - DownloadsTabFragment  
  - UpdatesTabFragment  
  - MyDownloadsFragment  
  - MarkStoriesCompletedFragment  

- [ ] **PR 10:** Admin & Developer Options  
  - AdministratorControlsFragment  
  - AdminSettingsDialogFragment  
  - DeveloperOptionsFragment  
  - PlatformParametersFragment  
  - FeatureFlagsFragment  

- [ ] **PR 11:** Settings & Help  
  - AppLanguageFragment  
  - AudioLanguageFragment  
  - ReadingTextSizeFragment  
  - HelpFragment  
  - FAQListFragment  

- [ ] **PR 12:** About & Policies  
  - AppVersionFragment  
  - PoliciesFragment  
  - LicenseListFragment  
  - LicenseTextViewerFragment  
  - ThirdPartyDependencyListFragment  

- [ ] **PR 13:** Event Logs & Misc  
  - ViewEventLogsFragment  
  - SpotlightFragment  
  - ProfileAndDeviceIdFragment  
  - ProgressDatabaseFullDialogFragment  
  - PendingChangesDialogFragment  

- [ ] **PR 14:** Audio & Connectivity  
  - AudioFragment  
  - CellularAudioDialogFragment  
  - ForceNetworkTypeFragment  
  - BetaNoticeDialogFragment  
  - GeneralAvailabilityUpgradeNoticeDialogFragment  

- [ ] **PR 15:** App Deprecation Notices  
  - AutomaticAppDeprecationNoticeDialogFragment  
  - ForcedAppDeprecationNoticeDialogFragment  
  - OptionalAppDeprecationNoticeDialogFragment  
  - OsDeprecationNoticeDialogFragment  
  - AppRestartDialogFragment  

- [ ] **PR 16:** Profile Deletion & Logout  
  - ExitProfileDialogFragment  
  - ProfileDeleteSuccessDialogFragment  
  - ProfileEditDeletionDialogFragment  
  - LogoutDialogFragment  
  - ExitSurveyConfirmationDialogFragment  

- [ ] **PR 17:** Surveys  
  - SurveyFragment  
  - SurveyWelcomeDialogFragment  
  - SurveyOutroDialogFragment  

- [ ] **PR 18:** Classrooms & Misc Tests  
  - ClassroomListFragment  
  - ExplorationManagerFragment  
  - ExplorationTestActivityPresenter.TestFragment  
  - UnsavedExplorationDialogFragment  
  - OptionFragment  

---

### Possible Solutions

- Increase layout margins and view dimensions in XMLs where text is truncated.  
- Adjust `TextView` attributes (e.g., `minWidth`, `maxLines`, `ellipsize`) to prevent clipping.  
- Use `ConstraintLayout` properly to avoid fixed widths.  
- Ensure UI is tested in **portrait + landscape** on small and large screens.  

---

### PR Submission Directions

- For each PR, contributors must:  
  - Apply fixes for the assigned fragments (5 per PR).  
  - Provide **before/after screenshots** and an optional screen recording.  
  - Verify all text is fully visible at 200% font scaling.  

Here is an example screenshot of the **Topic Screen** at 200% (current issue):  
<img src="https://github.com/user-attachments/assets/f763b114-1bef-485c-a784-1fe8b76379e7" height="600">

**Comment by BenHenning** [comment]
I think it's fine not to block the next release on this (especially since it's quite time sensitive), since I expect a lot of apps are going to break with this change in behavior.

**Comment by anmoltrvd01** [comment]
Hi @adhiamboperes,
I’d like to take up PR 11 (Settings & Help) from this issue, if it’s available.

My plan is to:
-Enable 200% font scaling on an Android 14+ emulator
-Test the assigned fragments individually
-Fix any text truncation or overlap using ConstraintLayout adjustments and appropriate TextView attributes
-Provide before/after screenshots for verification

Please let me know if this approach looks good.
Thanks!

**Comment by adhiamboperes** [comment]
Hi @anmoltrvd01, this approach sounds good to me.

**Comment by adhiamboperes** [comment]
Re-opening since #6135 only fixed part of the issue.

**Comment by ghost** [comment]
Hi @adhiamboperes,
I’d like to take up **PR 12 (About & Policies)** from this issue, if it’s available.
I’ve previously completed PR 11 for this issue.

My plan is to:
* Enable 200% font scaling on an Android 14+ emulator
* Test all assigned fragments individually
* Fix any truncation/overlap issues using proper layout adjustments
* Provide before/after screenshots for verification

Please let me know if this works.
Thanks!

**Comment by adhiamboperes** [comment]
> Hi [@adhiamboperes](https://github.com/adhiamboperes), I’d like to take up PR 11 (Settings & Help) from this issue, if it’s available.
> 
> My plan is to: -Enable 200% font scaling on an Android 14+ emulator -Test the assigned fragments individually -Fix any text truncation or overlap using ConstraintLayout adjustments and appropriate TextView attributes -Provide before/after screenshots for verification
> 
> Please let me know if this approach looks good. Thanks!



@anmoltrvd01, in the previous PR, only one fragment was fixed. Were the others okay or not?

Going forward, please add screenshots showing all the fragments in the package that you are working on, especially if they don't need a fix. We will need these as proof when closing the issue after all the packages have been audited.

**Comment by ghost** [comment]
Hi @adhiamboperes,

While re-checking the fragments, I noticed that although everything works correctly with English at 200% font scaling, switching to other languages (e.g., Kiswahili, Portuguese) introduces additional truncation issues in some fragments due to longer text.

The AudioLanguageFragment fix works as expected (marquee), but other fragments may need similar adjustments for full localization support.

### English  
<details>
<summary>Adding screenshots for all fragments in my previous PR (PR 11: Settings & Help) with 200% font scaling using English.</summary>

- AppLanguageFragment – no issues observed

<img width="374" height="784" alt="Image" src="https://github.com/user-attachments/assets/f5e8c64f-6ef7-4d9e-a2b8-025e0373fe0f" />

- AudioLanguageFragment – fixed (marquee applied)

<img width="377" height="783" alt="Image" src="https://github.com/user-attachments/assets/567334b6-9685-404e-9a98-fde83c9d7b1e" />

- ReadingTextSizeFragment – no issues observed

<img width="374" height="781" alt="Image" src="https://github.com/user-attachments/assets/d4474a9b-4eec-4293-8d36-75cce9eba358" />

- HelpFragment – no issues observed

<img width="374" height="783" alt="Image" src="https://github.com/user-attachments/assets/066fbc8e-2c7f-488f-9c76-6d1bb002286c" />

- FAQListFragment – no issues observed

<img width="374" height="778" alt="Image" src="https://github.com/user-attachments/assets/902d6b1a-3b03-4f31-9a32-5db2533084b4" />
</details>
---

Additionally, I tested with other languages (e.g., Kiswahili, Portuguese) and noticed that some UI elements (especially toolbar titles) may still experience truncation due to longer text.

### Kiswahili
<details>
<summary>Text expansion leads to overflow/truncation in toolbar</summary>

<img width="372" height="798" alt="Image" src="https://github.com/user-attachments/assets/5a2acf1d-2de1-496a-92f8-a81e7ae5b33f" />
</details>

### Portuguese 
<details>
<summary>Toolbar title truncation observed due to longer text</summary>

<img width="377" height="782" alt="Image" src="https://github.com/user-attachments/assets/ced64130-f1db-4029-bbaf-b9c29fe27e8d" />
</details>
---

**These issues appear due to increased text length in localized strings.**

Please let me know if you'd prefer I address these in this PR or create a follow-up PR.

Thanks!

**Comment by ghost** [comment]
Hi @adhiamboperes, I've raised PR #6251 as a follow-up to #6135 for PR 11 (Settings & Help).
Please let me know if everything looks good!

Thanks!

**Comment by ghost** [comment]
Hi @adhiamboperes, the bot is marking PR #6251 as draft because I'm not assigned to issue #5607. Would it be possible to assign me here as well?

Thanks!
